using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InterviewHub.API.Models;

public enum QuestionSource
{
    Auto = 0,
    Manual = 1
}

// Represents an interview question stored in the database.
// Questions can be generated by AI from job descriptions or created manually by admins.
// Each question is linked to a specific Skill (like "React" or "Communication").
public class Question
{
    [Key]
    public int QuestionId { get; set; }

    // Nullable: null for admin-created questions, set for job-specific questions
    public int? EmailId { get; set; }

    [ForeignKey("EmailId")]
    public virtual JobEmail? JobEmail { get; set; }

    public int? SkillId { get; set; }

    [ForeignKey("SkillId")]
    public virtual Skill? Skill { get; set; }

    [Required]
    [MaxLength(1000)]
    public string QuestionText { get; set; } = string.Empty;

    public QuestionType QuestionType { get; set; } = QuestionType.Technical;

    public QuestionDifficulty Difficulty { get; set; } = QuestionDifficulty.Medium;

    public bool IsFavorite { get; set; } = false;

    [MaxLength(500)]
    public string? SampleAnswer { get; set; }

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    // Admin management fields
    // IsAI: true if generated by Gemini AI, false if manually created by admin
    public bool IsAI { get; set; } = true;
    
    // IsApproved: admin can approve/reject auto-generated questions
    public bool IsApproved { get; set; } = true;
    
    // Which admin approved this question (nullable)
    public int? ApprovedBy { get; set; }
    
    public DateTime? ApprovedAt { get; set; }
    
    public bool IsDeleted { get; set; } = false;
    
    // Quality score from 0-100, used for ranking questions
    [Range(0, 100)]
    public int QualityScore { get; set; } = 0;

    // How many times this question has been used in interviews
    public int UsageCount { get; set; } = 0;

    // Source: Auto (AI-generated) or Manual (admin-created)
    public QuestionSource Source { get; set; } = QuestionSource.Auto;
}

